### PR TITLE
Fix seo thumbnails

### LINKED ISSUE #159: Fix SEO thumbnails
Check https://hack.uclaacm.com/teams on messenger:

image

I think the missing of the thumbnail will lead Facebook to just grab whatever they see as the first image. Let's just add a default using the hack banner in the SEO component as default. 

Helpful tool: https://metatags.io/

### PR DESCRIPTION
**Pull request by EinarBalan**
Added default image 
Closes #159

### CODE REVIEW

**Comment by EinarBalan** [comment]
Screen Shot 2021-02-14 at 8 33 24 PM
working wooo

File: src/components/SEO.js [hunk 1]
```diff
@@ -49,6 +50,14 @@ function SEO({ description, lang, meta, title, type }) {
 					name: 'twitter:card',
 					content: 'summary'
 				},
+				{
+					name: 'og:image',
```
Comment (TimothyGu) [inline src/components/SEO.js:54]:
```suggestion
					property: 'og:image',
```

The [Open Graph spec](https://ogp.me/) says it should be `property=`, while Twitter uses `name=`.

**Review by TimothyGu — COMMENTED** [review]
Is there something we can do to ensure that src/images/event/hack-banner.png and static/image/hack-banner.png stay in sync in the future? We don't want to accidentally update one but not the other.

Also, is there a SVG version of the banner available?

File: src/components/SEO.js [hunk 2]
```diff
@@ -49,6 +50,14 @@ function SEO({ description, lang, meta, title, type }) {
 					name: 'twitter:card',
 					content: 'summary'
```
Comment (TimothyGu) [inline src/components/SEO.js:51]: Check out Twitter documentation here:

* https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary
* https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image

We have twitter:card set to `summary` right now, which requires a 1:1 aspect ratio image. If we want to use the banner (closer to 2:1), then we should instead set it to be `summary_large_image`.

You can use the [Twitter validator](https://cards-dev.twitter.com/validator) to check if it worked. Right now, it looks like

image

File: src/components/SEO.js (hunk 1 above)
Comment (EinarBalan) [reply src/components/SEO.js:54]: > Is there something we can do to ensure that src/images/event/hack-banner.png and static/image/hack-banner.png stay in sync in the future? We don't want to accidentally update one but not the other.
> 
> Also, is there a SVG version of the banner available?

"We can get an SVG, but why do we need it?" - Jody

File: src/components/SEO.js (hunk 2 above)
Comment (EinarBalan) [reply src/components/SEO.js]: we can't get it to work on twitter rip

File: src/components/SEO.js (hunk 1 above)
Comment (TimothyGu) [reply src/components/SEO.js]: > "We can get an SVG, but why do we need it?" - Jody

Good to always have a source file in case we need to modify it (or generate higher resolution PNGs) in the future.

Comment (GalenWong) [reply src/components/SEO.js]: We have it in figma which we can extract the svg from it.

**Review by TimothyGu — APPROVED** [review]
